// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using scripture_hub_server.Infrastructure.Data.Context;

#nullable disable

namespace scripture_hub_server.Migrations
{
    [DbContext(typeof(ScriptureHubDbContext))]
    [Migration("20260628213545_CleanSchemaSync")]
    partial class CleanSchemaSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ScriptureHub")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("scripture_hub_server.Infrastructure.Data.Models.Bible.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abbreviation");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Testament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("testament");

                    b.Property<string>("TranslationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("translation_id");

                    b.HasKey("Id");

                    b.ToTable("Books", "ScriptureHub");
                });

            modelBuilder.Entity("scripture_hub_server.Infrastructure.Data.Models.Bible.Translations", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("api_url");

                    b.Property<string>("License")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("license");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PaymentTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_tier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("translation_type_id");

                    b.Property<bool>("UsesApi")
                        .HasColumnType("bit")
                        .HasColumnName("uses_api");

                    b.HasKey("Id");

                    b.ToTable("Translations", "ScriptureHub");
                });

            modelBuilder.Entity("scripture_hub_server.Infrastructure.Data.Models.Bible.UserVerses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<int>("Chapter")
                        .HasColumnType("int")
                        .HasColumnName("chapter");

                    b.Property<DateTimeOffset>("DailyScriptureShownDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("daily_scripture_date");

                    b.Property<string>("HighlightColor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("highlight_color");

                    b.Property<bool>("IsDailyScripture")
                        .HasColumnType("bit")
                        .HasColumnName("daily_scripture");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("int")
                        .HasColumnName("verse");

                    b.HasKey("Id");

                    b.ToTable("UserVerses", "ScriptureHub");
                });

            modelBuilder.Entity("scripture_hub_server.Infrastructure.Data.Models.Bible.Verses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<int>("Chapter")
                        .HasColumnType("int")
                        .HasColumnName("chapter");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<string>("TranslationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("translation_id");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("int")
                        .HasColumnName("verse");

                    b.HasKey("Id");

                    b.ToTable("Verses", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
